TICKETS = [
    {'label': 'Magazine Luiza', 'value': 'MGLU3.SA'},
    {'label': 'Hapvida', 'value': 'HAPV3.SA'},
    {'label': 'Americanas', 'value': 'AMER3.SA'},
    {'label': 'Via', 'value': 'VIIA3.SA'},
    {'label': 'B3', 'value': 'B3SA3.SA'},
    {'label': 'Petrobras', 'value': 'PETR4.SA'},
    {'label': 'Banco do Brasil', 'value': 'BBAS3.SA'},
    {'label': 'Banco Bradesco', 'value': 'BBDC4.SA'},
    {'label': 'Itaú Unibanco', 'value': 'ITUB4.SA'},
    {'label': 'Cogna', 'value': 'COGN3.SA'},
    {'label': 'Ambev', 'value': 'ABEV3.SA'},
    {'label': 'Cielo', 'value': 'CIEL3.SA'},
    {'label': 'Lojas Renner', 'value': 'LREN3.SA'},
    {'label': 'Vale', 'value': 'VALE3.SA'},
    {'label': 'Raízen', 'value': 'RAIZ4.SA'},
    {'label': 'CVC', 'value': 'CVCB3.SA'},
    {'label': 'Itaúsa', 'value': 'ITSA4.SA'},
    {'label': 'CEMIG', 'value': 'CMIG4.SA'},
    {'label': 'Méliuz', 'value': 'CASH3.SA'},
    {'label': 'COPEL', 'value': 'CPLE6.SA'},
    {'label': 'Natura', 'value': 'NTCO3.SA'},
    {'label': 'Assaí', 'value': 'ASAI3.SA'},
    {'label': 'Lojas Marisa', 'value': 'AMAR3.SA'},
    {'label': 'Azul', 'value': 'AZUL4.SA'},
    {'label': 'Oi', 'value': 'OIBR3.SA'},
    {'label': 'Localiza', 'value': 'RENT3.SA'},
    {'label': 'RaiaDrogasil', 'value': 'RADL3.SA'},
    {'label': 'GOL', 'value': 'GOLL4.SA'},
    {'label': 'Ânima Educação', 'value': 'ANIM3.SA'},
    {'label': 'Petrobras', 'value': 'PETR3.SA'},
    {'label': 'Cosan', 'value': 'CSAN3.SA'},
    {'label': 'Eletrobras', 'value': 'ELET3.SA'},
    {'label': 'Grupo CCR', 'value': 'CCRO3.SA'},
    {'label': 'BRF', 'value': 'BRFS3.SA'},
    {'label': 'Marfrig', 'value': 'MRFG3.SA'},
    {'label': 'Metalúrgica Gerdau', 'value': 'GOAU4.SA'},
    {'label': 'Minerva', 'value': 'BEEF3.SA'},
    {'label': 'Rumo', 'value': 'RAIL3.SA'},
    {'label': 'Gerdau', 'value': 'GGBR4.SA'},
    {'label': 'Petz', 'value': 'PETZ3.SA'},
    {'label': 'Santos Brasil', 'value': 'STBP3.SA'},
    {'label': 'MRV', 'value': 'MRVE3.SA'},
    {'label': 'Equatorial Energia', 'value': 'EQTL3.SA'},
    {'label': 'PetroRio', 'value': 'PRIO3.SA'},
    {'label': 'Marcopolo', 'value': 'POMO4.SA'},
    {'label': 'Eneva', 'value': 'ENEV3.SA'},
    {'label': 'Carrefour Brasil', 'value': 'CRFB3.SA'},
    {'label': 'Ultrapar', 'value': 'UGPA3.SA'},
    {'label': 'Usiminas', 'value': 'USIM5.SA'},
    {'label': 'Grupo Soma', 'value': 'SOMA3.SA'},
    {'label': 'JBS', 'value': 'JBSS3.SA'},
    {'label': 'EcoRodovias', 'value': 'ECOR3.SA'},
    {'label': 'Vibra Energia', 'value': 'VBBR3.SA'},
    {'label': 'TIM', 'value': 'TIMS3.SA'},
    {'label': 'Banco Bradesco', 'value': 'BBDC3.SA'},
    {'label': 'Cyrela', 'value': 'CYRE3.SA'},
    {'label': 'Embraer', 'value': 'EMBR3.SA'},
    {'label': 'Multilaser', 'value': 'MLAS3.SA'},
    {'label': 'WEG', 'value': 'WEGE3.SA'},
    {'label': '3R Petroleum', 'value': 'RRRP3.SA'},
    {'label': 'Rede D\'Or', 'value': 'RDOR3.SA'},
    {'label': 'Locaweb', 'value': 'LWSA3.SA'},
    {'label': 'Alpargatas', 'value': 'ALPA4.SA'},
    {'label': 'Light', 'value': 'LIGT3.SA'},
    {'label': 'Multiplan', 'value': 'MULT3.SA'},
    {'label': 'CSN Mineração', 'value': 'CMIN3.SA'},
    {'label': 'Totvs', 'value': 'TOTS3.SA'},
    {'label': 'Siderúrgica Nacional', 'value': 'CSNA3.SA'},
    {'label': 'Movida', 'value': 'MOVI3.SA'},
    {'label': 'Lojas Quero-Quero', 'value': 'LJQQ3.SA'},
    {'label': 'Qualicorp', 'value': 'QUAL3.SA'},
    {'label': 'Aeris', 'value': 'AERI3.SA'},
    {'label': 'Simpar', 'value': 'SIMH3.SA'},
    {'label': 'BB Seguridade', 'value': 'BBSE3.SA'},
    {'label': 'Eletrobras', 'value': 'ELET6.SA'},
    {'label': 'Sequoia Logística', 'value': 'SEQL3.SA'},
    {'label': 'Dexco', 'value': 'DXCO3.SA'},
    {'label': 'Hidrovias do Brasil', 'value': 'HBSA3.SA'},
    {'label': 'Hypera', 'value': 'HYPE3.SA'},
    {'label': 'Grupo Vamos', 'value': 'VAMO3.SA'},
    {'label': 'Grupo Mateus', 'value': 'GMAT3.SA'},
    {'label': 'Klabin', 'value': 'KLBN4.SA'},
    {'label': 'Suzano', 'value': 'SUZB3.SA'},
    {'label': 'CBA', 'value': 'CBAV3.SA'},
    {'label': 'Caixa Seguridade', 'value': 'CXSE3.SA'},
    {'label': 'Aliansce Sonae', 'value': 'ALSO3.SA'},
    {'label': 'Banco Pan', 'value': 'BPAN4.SA'},
    {'label': 'Construtora Tenda', 'value': 'TEND3.SA'},
    {'label': 'COPEL', 'value': 'CPLE3.SA'},
    {'label': 'Randon', 'value': 'RAPT4.SA'},
    {'label': 'Odontoprev', 'value': 'ODPV3.SA'},
    {'label': 'C&A', 'value': 'CEAB3.SA'},
    {'label': 'Espaçolaser', 'value': 'ESPA3.SA'},
    {'label': 'EZTEC', 'value': 'EZTC3.SA'},
    {'label': 'Viver', 'value': 'VIVR3.SA'},
    {'label': 'Sanepar', 'value': 'SAPR4.SA'},
    {'label': 'EDP Brasil', 'value': 'ENBR3.SA'},
    {'label': 'YDUQS', 'value': 'YDUQ3.SA'},
    {'label': 'Vivara', 'value': 'VIVA3.SA'},
    {'label': 'Fleury', 'value': 'FLRY3.SA'},
    {'label': 'PetroRecôncavo', 'value': 'RECV3.SA'},
    {'label': 'Grupo SBF', 'value': 'SBFG3.SA'},
    {'label': 'Inepar', 'value': 'INEP3.SA'},
    {'label': 'Transmissão Paulista', 'value': 'TRPL4.SA'},
    {'label': 'Direcional', 'value': 'DIRR3.SA'},
    {'label': 'Vivo', 'value': 'VIVT3.SA'},
    {'label': 'BK Brasil', 'value': 'ZAMP3.SA'},
    {'label': 'JHSF', 'value': 'JHSF3.SA'},
    {'label': 'Bradespar', 'value': 'BRAP4.SA'},
    {'label': 'Sabesp', 'value': 'SBSP3.SA'},
    {'label': 'Positivo', 'value': 'POSI3.SA'},
    {'label': 'Intelbras', 'value': 'INTB3.SA'},
    {'label': 'Grupo Pão de Açúcar', 'value': 'PCAR3.SA'},
    {'label': 'Smart Fit', 'value': 'SMFT3.SA'},
    {'label': 'AES Brasil', 'value': 'AESB3.SA'},
    {'label': 'Arezzo', 'value': 'ARZZ3.SA'},
    {'label': 'Braskem', 'value': 'BRKM5.SA'},
    {'label': 'Banrisul', 'value': 'BRSR6.SA'},
    {'label': 'ENGIE', 'value': 'EGIE3.SA'},
    {'label': 'Guararapes', 'value': 'GUAR3.SA'},
    {'label': 'COPASA', 'value': 'CSMG3.SA'},
    {'label': 'Mills', 'value': 'MILS3.SA'},
    {'label': 'CPFL Energia', 'value': 'CPFE3.SA'},
    {'label': 'Banco Modal', 'value': 'MODL3.SA'},
    {'label': 'Grendene', 'value': 'GRND3.SA'},
    {'label': 'IRB Brasil RE', 'value': 'IRBR3.SA'},
    {'label': 'São Martinho', 'value': 'SMTO3.SA'},
    {'label': 'Neoenergia', 'value': 'NEOE3.SA'},
    {'label': 'M. Dias Branco', 'value': 'MDIA3.SA'},
    {'label': 'GetNinjas', 'value': 'NINJ3.SA'},
    {'label': 'Iochpe-Maxion', 'value': 'MYPK3.SA'},
    {'label': 'Ambipar', 'value': 'AMBP3.SA'},
    {'label': 'Kepler Weber', 'value': 'KEPL3.SA'},
    {'label': 'GPS', 'value': 'GGPS3.SA'},
    {'label': 'Traders Club', 'value': 'TRAD3.SA'},
    {'label': 'Cury', 'value': 'CURY3.SA'},
    {'label': 'Porto Seguro', 'value': 'PSSA3.SA'},
    {'label': 'Enjoei', 'value': 'ENJU3.SA'},
    {'label': 'Neogrid', 'value': 'NGRD3.SA'},
    {'label': 'Enauta', 'value': 'ENAT3.SA'},
    {'label': 'Camil Alimentos', 'value': 'CAML3.SA'},
    {'label': 'Oncoclínicas', 'value': 'ONCO3.SA'},
    {'label': 'Trisul', 'value': 'TRIS3.SA'},
    {'label': 'Portobello', 'value': 'PTBL3.SA'},
    {'label': 'Recrusul', 'value': 'RCSL3.SA'},
    {'label': 'SYN', 'value': 'SYNE3.SA'},
    {'label': 'Plano&Plano', 'value': 'PLPL3.SA'},
    {'label': 'IMC Alimentação', 'value': 'MEAL3.SA'},
    {'label': 'Tupy', 'value': 'TUPY3.SA'},
    {'label': 'Gafisa', 'value': 'GFSA3.SA'},
    {'label': 'Irani', 'value': 'RANI3.SA'},
    {'label': '3tentos', 'value': 'TTEN3.SA'},
    {'label': 'SLC Agrícola', 'value': 'SLCE3.SA'},
    {'label': 'Helbor', 'value': 'HBOR3.SA'},
    {'label': 'Taurus', 'value': 'TASA4.SA'},
    {'label': 'Ser Educacional', 'value': 'SEER3.SA'},
    {'label': 'Infracommerce', 'value': 'IFCM3.SA'},
    {'label': 'Lupatech', 'value': 'LUPA3.SA'},
    {'label': 'Azevedo & Travassos', 'value': 'AZEV4.SA'},
    {'label': 'Banco BMG', 'value': 'BMGB4.SA'},
    {'label': 'Klabin', 'value': 'KLBN3.SA'},
    {'label': 'Dimed', 'value': 'PNVL3.SA'},
    {'label': 'Even', 'value': 'EVEN3.SA'},
    {'label': 'Pague Menos', 'value': 'PGMN3.SA'},
    {'label': 'BrasilAgro', 'value': 'AGRO3.SA'},
    {'label': 'ClearSale', 'value': 'CLSA3.SA'},
    {'label': 'Recrusul', 'value': 'RCSL4.SA'},
    {'label': 'Wiz Soluções', 'value': 'WIZC3.SA'},
    {'label': 'Sinqia', 'value': 'SQIA3.SA'},
    {'label': 'Boa Vista', 'value': 'BOAS3.SA'},
    {'label': 'Indústrias ROMI', 'value': 'ROMI3.SA'},
    {'label': 'Inepar', 'value': 'INEP4.SA'},
    {'label': 'Marcopolo', 'value': 'POMO3.SA'},
    {'label': 'Dasa', 'value': 'DASA3.SA'},
    {'label': 'Banco ABC Brasil', 'value': 'ABCB4.SA'},
    {'label': 'Viveo', 'value': 'VVEO3.SA'},
    {'label': 'Jalles Machado', 'value': 'JALL3.SA'},
    {'label': 'Itaú Unibanco', 'value': 'ITUB3.SA'},
    {'label': 'Taesa', 'value': 'TAEE4.SA'},
    {'label': 'Mitre Realty', 'value': 'MTRE3.SA'},
    {'label': 'Lopes', 'value': 'LPSB3.SA'},
    {'label': 'Cruzeiro do Sul Educacional', 'value': 'CSED3.SA'},
    {'label': 'Mobly', 'value': 'MBLY3.SA'},
    {'label': 'Technos', 'value': 'TECN3.SA'},
    {'label': 'Schulz', 'value': 'SHUL4.SA'},
    {'label': 'Estapar', 'value': 'ALPK3.SA'},
    {'label': 'Coelce', 'value': 'COCE5.SA'},
    {'label': 'Valid', 'value': 'VLID3.SA'},
    {'label': 'JSL', 'value': 'JSLG3.SA'},
    {'label': 'Brisanet', 'value': 'BRIT3.SA'},
    {'label': 'LOG CP', 'value': 'LOGG3.SA'},
    {'label': 'Eternit', 'value': 'ETER3.SA'},
    {'label': 'Lavvi Incorporadora', 'value': 'LAVV3.SA'},
    {'label': 'Hermes Pardini', 'value': 'PARD3.SA'},
    {'label': 'Vulcabras', 'value': 'VULC3.SA'},
    {'label': 'Fras-le', 'value': 'FRAS3.SA'},
    {'label': 'Mater Dei', 'value': 'MATD3.SA'},
    {'label': 'Wilson Sons', 'value': 'PORT3.SA'},
    {'label': 'Alliar', 'value': 'AALR3.SA'},
    {'label': 'Sanepar', 'value': 'SAPR3.SA'},
    {'label': 'PINE', 'value': 'PINE4.SA'},
    {'label': 'Orizon', 'value': 'ORVR3.SA'},
    {'label': 'Tegma', 'value': 'TGMA3.SA'},
    {'label': 'Armac', 'value': 'ARML3.SA'},
    {'label': 'SPRINGS', 'value': 'SGPS3.SA'},
    {'label': 'Unipar', 'value': 'UNIP6.SA'},
    {'label': 'Bemobi', 'value': 'BMOB3.SA'},
    {'label': 'Time For Fun', 'value': 'SHOW3.SA'},
    {'label': 'Triunfo', 'value': 'TPIS3.SA'},
    {'label': 'Dexxos', 'value': 'DEXP3.SA'},
    {'label': 'Blau Farmacêutica', 'value': 'BLAU3.SA'},
    {'label': 'CEMIG', 'value': 'CMIG3.SA'},
    {'label': 'Mahle Metal Leve', 'value': 'LEVE3.SA'},
    {'label': 'Vittia', 'value': 'VITT3.SA'},
    {'label': 'Usiminas', 'value': 'USIM3.SA'},
    {'label': 'OceanPact', 'value': 'OPCT3.SA'},
    {'label': 'Boa Safra Sementes', 'value': 'SOJA3.SA'},
    {'label': 'PDG Realty', 'value': 'PDGR3.SA'},
    {'label': 'Kora Saúde', 'value': 'KRSA3.SA'},
    {'label': 'Eletromidia', 'value': 'ELMD3.SA'},
    {'label': 'HBR Realty', 'value': 'HBRE3.SA'},
    {'label': 'Track & Field', 'value': 'TFCO4.SA'},
    {'label': 'Itaúsa', 'value': 'ITSA3.SA'},
    {'label': 'Taesa', 'value': 'TAEE3.SA'},
    {'label': 'Ferbasa', 'value': 'FESA4.SA'},
    {'label': 'Moura Dubeux', 'value': 'MDNE3.SA'},
    {'label': 'Profarma', 'value': 'PFRM3.SA'},
    {'label': 'Melnick', 'value': 'MELK3.SA'},
    {'label': 'Unifique', 'value': 'FIQE3.SA'},
    {'label': 'PRINER', 'value': 'PRNR3.SA'},
    {'label': 'Westwing', 'value': 'WEST3.SA'},
    {'label': 'Log-In', 'value': 'LOGN3.SA'},
    {'label': 'Banco Santander', 'value': 'SANB3.SA'},
    {'label': 'CSU Cardsystem', 'value': 'CSUD3.SA'},
    {'label': 'Santanense', 'value': 'CTSA4.SA'},
    {'label': 'Dotz', 'value': 'DOTZ3.SA'},
    {'label': 'Azevedo & Travassos', 'value': 'AZEV3.SA'},
    {'label': 'Tecnisa', 'value': 'TCSA3.SA'},
    {'label': 'Banco Santander', 'value': 'SANB4.SA'},
    {'label': 'Cedro Têxtil', 'value': 'CEDO4.SA'},
    {'label': 'Metalúrgica Gerdau', 'value': 'GOAU3.SA'},
    {'label': 'Rossi Residencial', 'value': 'RSID3.SA'},
    {'label': 'BR Properties', 'value': 'BRPR3.SA'},
    {'label': 'Jereissati Participações', 'value': 'IGTI3.SA'},
    {'label': 'Iguatemi', 'value': 'IGTI3.SA'},
    {'label': 'Desktop', 'value': 'DESK3.SA'},
    {'label': 'Paranapanema', 'value': 'PMAM3.SA'},
    {'label': 'WDC Networks', 'value': 'LVTC3.SA'},
    {'label': 'OSX BRASIL', 'value': 'OSXB3.SA'},
    {'label': 'Fertilizantes Heringer', 'value': 'FHER3.SA'},
    {'label': 'Oi', 'value': 'OIBR4.SA'},
    {'label': 'Taurus', 'value': 'TASA3.SA'},
    {'label': 'Bahema', 'value': 'BAHI3.SA'},
    {'label': 'Renova Energia', 'value': 'RNEW3.SA'},
    {'label': 'Padtec', 'value': 'PDTC3.SA'},
    {'label': 'Bradespar', 'value': 'BRAP3.SA'},
    {'label': 'Alper', 'value': 'APER3.SA'},
    {'label': 'Alupar', 'value': 'ALUP4.SA'},
    {'label': 'Renova Energia', 'value': 'RNEW4.SA'},
    {'label': 'Gerdau', 'value': 'GGBR3.SA'},
    {'label': 'Bombril', 'value': 'BOBR4.SA'},
    {'label': 'Saraiva', 'value': 'SLED4.SA'},
    {'label': 'CEB', 'value': 'CEBR6.SA'},
    {'label': 'Unicasa', 'value': 'UCAS3.SA'},
    {'label': 'Electro Aço Altona', 'value': 'EALT4.SA'},
    {'label': 'D1000 Varejo Farma', 'value': 'DMVF3.SA'},
    {'label': 'Biomm', 'value': 'BIOM3.SA'},
    {'label': 'Energisa', 'value': 'ENGI4.SA'},
    {'label': 'Ourofino Saúde Animal', 'value': 'OFSA3.SA'},
    {'label': 'Alupar', 'value': 'ALUP3.SA'},
    {'label': 'João Fortes', 'value': 'JFEN3.SA'},
    {'label': 'Coteminas', 'value': 'CTNM4.SA'},
    {'label': 'Alfa Investimento', 'value': 'BRIV4.SA'},
    {'label': 'Unipar', 'value': 'UNIP3.SA'},
    {'label': 'AgroGalaxy', 'value': 'AGXY3.SA'},
    {'label': 'Banestes', 'value': 'BEES3.SA'},
    {'label': 'Allied', 'value': 'ALLD3.SA'},
    {'label': 'Brasil Brokers', 'value': 'NEXP3.SA'},
    {'label': 'Banco BTG Pactual', 'value': 'BPAC5.SA'},
    {'label': 'ATMASA', 'value': 'ATMP3.SA'},
    {'label': 'Terra Santa', 'value': 'LAND3.SA'},
    {'label': 'LE LIS BLANC', 'value': 'VSTE3.SA'},
    {'label': 'RNI', 'value': 'RDNI3.SA'},
    {'label': 'Whirlpool', 'value': 'WHRL4.SA'},
    {'label': 'Alphaville', 'value': 'AVLL3.SA'},
    {'label': 'Eucatex', 'value': 'EUCA4.SA'},
    {'label': 'Telebrás', 'value': 'TELB4.SA'},
    {'label': 'ATOM', 'value': 'ATOM3.SA'},
    {'label': 'Jereissati Participações', 'value': 'IGTI4.SA'},
    {'label': 'Iguatemi', 'value': 'IGTI4.SA'},
    {'label': 'Braskem', 'value': 'BRKM3.SA'},
    {'label': 'Energisa', 'value': 'ENGI3.SA'},
    {'label': 'Refinaria de Manguinhos', 'value': 'RPMG3.SA'},
    {'label': 'Santanense', 'value': 'CTSA3.SA'},
    {'label': 'Banrisul', 'value': 'BRSR3.SA'},
    {'label': 'CELESC', 'value': 'CLSC4.SA'},
    {'label': 'Bardella', 'value': 'BDLL4.SA'},
    {'label': 'Randon', 'value': 'RAPT3.SA'},
    {'label': 'CEB', 'value': 'CEBR3.SA'},
    {'label': 'Banco BTG Pactual', 'value': 'BPAC3.SA'},
    {'label': 'Cambuci', 'value': 'CAMB3.SA'},
    {'label': 'Pettenati', 'value': 'PTNT4.SA'},
    {'label': 'São Carlos', 'value': 'SCAR3.SA'},
    {'label': 'METISA', 'value': 'MTSA4.SA'},
    {'label': 'Dexxos', 'value': 'DEXP4.SA'},
    {'label': 'CEB', 'value': 'CEBR5.SA'},
    {'label': 'Banestes', 'value': 'BEES4.SA'},
    {'label': 'Alfa Financeira', 'value': 'CRIV3.SA'},
    {'label': 'Alpargatas', 'value': 'ALPA3.SA'},
    {'label': 'Equatorial Maranhão', 'value': 'EQMA3B.SA'},
    {'label': 'Grazziotin', 'value': 'CGRA4.SA'},
    {'label': 'Pettenati', 'value': 'PTNT3.SA'},
    {'label': 'Minupar', 'value': 'MNPR3.SA'},
    {'label': 'Alfa Holdings', 'value': 'RPAD6.SA'},
    {'label': 'Tronox Pigmentos', 'value': 'CRPG5.SA'},
    {'label': 'Haga', 'value': 'HAGA4.SA'},
    {'label': 'IGB S/A', 'value': 'IGBR3.SA'},
    {'label': 'Saraiva', 'value': 'SLED3.SA'},
    {'label': 'Hotéis Othon', 'value': 'HOOT4.SA'},
    {'label': 'Rio Paranapanema Energia', 'value': 'GEPA4.SA'},
    {'label': 'Sansuy', 'value': 'SNSY5.SA'},
    {'label': 'Mundial', 'value': 'MNDL3.SA'},
    {'label': 'Equatorial Pará', 'value': 'EQPA3.SA'},
    {'label': 'Haga', 'value': 'HAGA3.SA'},
    {'label': 'Bardella', 'value': 'BDLL3.SA'},
    {'label': 'Banco da Amazônia', 'value': 'BAZA3.SA'},
    {'label': 'EPAR3', 'value': 'EPAR3.SA'},
    {'label': 'EMAE', 'value': 'EMAE4.SA'},
    {'label': 'Banco Mercantil do Brasil', 'value': 'BMEB4.SA'},
    {'label': 'Whirlpool', 'value': 'WHRL3.SA'},
    {'label': 'Metalúrgica Riosulense', 'value': 'RSUL4.SA'},
    {'label': 'Eucatex', 'value': 'EUCA3.SA'},
    {'label': 'Transmissão Paulista', 'value': 'TRPL3.SA'},
    {'label': 'Alfa Financeira', 'value': 'CRIV4.SA'},
    {'label': 'Rede Energia', 'value': 'REDE3.SA'},
    {'label': 'WLM', 'value': 'WLMM4.SA'},
    {'label': 'Wetzel', 'value': 'MWET4.SA'},
    {'label': 'Tronox Pigmentos', 'value': 'CRPG6.SA'},
    {'label': 'Telebrás', 'value': 'TELB3.SA'},
    {'label': 'Comgás', 'value': 'CGAS5.SA'},
    {'label': 'COSERN', 'value': 'CSRN3.SA'},
    {'label': 'Panatlântica', 'value': 'PATI4.SA'},
    {'label': 'Banese', 'value': 'BGIP4.SA'},
    {'label': 'Baumer', 'value': 'BALM4.SA'},
    {'label': 'CELESC', 'value': 'CLSC3.SA'},
    {'label': 'Rio Paranapanema Energia', 'value': 'GEPA3.SA'},
    {'label': 'COPEL', 'value': 'CPLE5.SA'},
    {'label': 'Banco de Brasília', 'value': 'BSLI4.SA'},
    {'label': 'Consórcio Alfa', 'value': 'BRGE7.SA'},
    {'label': 'Pomi Frutas', 'value': 'FRTA3.SA'},
    {'label': 'Participações Aliança da Bahia', 'value': 'PEAB4.SA'},
    {'label': 'COELBA', 'value': 'CEEB3.SA'},
    {'label': 'Grazziotin', 'value': 'CGRA3.SA'},
    {'label': 'Banrisul', 'value': 'BRSR5.SA'},
    {'label': 'Consórcio Alfa', 'value': 'BRGE11.SA'},
    {'label': 'Electro Aço Altona', 'value': 'EALT3.SA'},
    {'label': 'Karsten', 'value': 'CTKA4.SA'},
    {'label': 'Döhler', 'value': 'DOHL4.SA'},
    {'label': 'Elektro', 'value': 'EKTR4.SA'},
    {'label': 'Josapar', 'value': 'JOPA4.SA'},
    {'label': 'Banese', 'value': 'BGIP3.SA'},
    {'label': 'Josapar', 'value': 'JOPA3.SA'},
    {'label': 'Usiminas', 'value': 'USIM6.SA'},
    {'label': 'Banco de Brasília', 'value': 'BSLI3.SA'},
    {'label': 'Alfa Investimento', 'value': 'BRIV3.SA'},
    {'label': 'Alfa Holdings', 'value': 'RPAD5.SA'},
    {'label': 'Nordon', 'value': 'NORD3.SA'},
    {'label': 'Monark', 'value': 'BMKS3.SA'},
    {'label': 'Cedro Têxtil', 'value': 'CEDO3.SA'},
    {'label': 'Mangels', 'value': 'MGEL4.SA'},
    {'label': 'Teka', 'value': 'TEKA4.SA'},
    {'label': 'Monteiro Aranha', 'value': 'MOAR3.SA'},
    {'label': 'Afluente T', 'value': 'AFLT3.SA'},
    {'label': 'Plascar', 'value': 'PLAS3.SA'},
    {'label': 'Energisa MT', 'value': 'ENMT3.SA'},
    {'label': 'General Shopping & Outlets', 'value': 'GSHP3.SA'},
    {'label': 'Unipar', 'value': 'UNIP5.SA'},
    {'label': 'Estrela', 'value': 'ESTR4.SA'},
    {'label': 'Ampla Energia', 'value': 'CBEE3.SA'},
    {'label': 'Banco Mercantil do Brasil', 'value': 'BMEB3.SA'},
    {'label': 'Metalfrio', 'value': 'FRIO3.SA'},
    {'label': 'CR2', 'value': 'CRDE3.SA'},
    {'label': 'Hercules', 'value': 'HETA4.SA'},
    {'label': 'Trevisa', 'value': 'LUXM4.SA'},
    {'label': 'Banco do Nordeste', 'value': 'BNBR3.SA'},
    {'label': 'Ferbasa', 'value': 'FESA3.SA'},
    {'label': 'COSERN', 'value': 'CSRN5.SA'},
    {'label': 'COSERN', 'value': 'CSRN6.SA'},
    {'label': 'Adolpho Lindenberg', 'value': 'CALI3.SA'},
    {'label': 'Eletropar', 'value': 'LIPR3.SA'},
    {'label': 'Energisa MT', 'value': 'ENMT4.SA'},
    {'label': 'Banco Mercantil de Investimentos', 'value': 'BMIN4.SA'},
    {'label': 'Excelsior', 'value': 'BAUH4.SA'},
    {'label': 'Habitasul', 'value': 'HBTS5.SA'},
    {'label': 'Alfa Holdings', 'value': 'RPAD3.SA'},
    {'label': 'Participações Aliança da Bahia', 'value': 'PEAB3.SA'},
    {'label': 'São Paulo Turismo', 'value': 'AHEB3.SA'},
    {'label': 'Comgás', 'value': 'CGAS3.SA'},
    {'label': 'COELBA', 'value': 'CEEB5.SA'},
    {'label': 'Consórcio Alfa', 'value': 'BRGE12.SA'},
    {'label': 'Mercantil do Brasil Financeira', 'value': 'MERC4.SA'},
    {'label': 'Cia. de Seg. Aliança da Bahia', 'value': 'CSAB3.SA'},
    {'label': 'Cia. de Seg. Aliança da Bahia', 'value': 'CSAB4.SA'},
    {'label': 'Consórcio Alfa', 'value': 'BRGE3.SA'},
    {'label': 'Cemepe', 'value': 'MAPT4.SA'},
    {'label': 'Tekno', 'value': 'TKNO4.SA'},
    {'label': 'CEEE D', 'value': 'CEED3.SA'},
    {'label': 'Coteminas', 'value': 'CTNM3.SA'},
    {'label': 'Sansuy', 'value': 'SNSY3.SA'},
    {'label': 'Elektro', 'value': 'EKTR3.SA'},
    {'label': 'Braskem', 'value': 'BRKM6.SA'},
    {'label': 'CEEE D', 'value': 'CEED4.SA'},
    {'label': 'CELGPAR', 'value': 'GPAR3.SA'},
    {'label': 'Banco Mercantil de Investimentos', 'value': 'BMIN3.SA'},
    {'label': 'Baumer', 'value': 'BALM3.SA'},
    {'label': 'METISA', 'value': 'MTSA3.SA'},
    {'label': 'Consórcio Alfa', 'value': 'BRGE8.SA'},
    {'label': 'Cemepe', 'value': 'MAPT3.SA'},
    {'label': 'Dtcom', 'value': 'DTCY3.SA'},
    {'label': 'Sondotécnica', 'value': 'SOND5.SA'},
    {'label': 'Eletrobras', 'value': 'ELET5.SA'},
    {'label': 'Panatlântica', 'value': 'PATI3.SA'},
    {'label': 'Equatorial Pará', 'value': 'EQPA7.SA'},
    {'label': 'WLM', 'value': 'WLMM3.SA'},
    {'label': 'Consórcio Alfa', 'value': 'BRGE6.SA'},
    {'label': 'Coelce', 'value': 'COCE3.SA'},
    {'label': 'DMFN3', 'value': 'DMFN3.SA'},
    {'label': 'Sondotécnica', 'value': 'SOND6.SA'},
    {'label': 'MRS Logística', 'value': 'MRSA5B.SA'},
    {'label': 'WIZS3', 'value': 'WIZS3.SA'},
    {'label': 'LLIS3', 'value': 'LLIS3.SA'},
    {'label': 'Melhoramentos', 'value': 'MSPA3.SA'},
    {'label': 'BRMalls', 'value': 'BRML3.SA'},
    {'label': 'Dommo Energia', 'value': 'DMMO3.SA'},
    {'label': 'Equatorial Pará', 'value': 'EQPA5.SA'},
    {'label': 'Getnet', 'value': 'GETT3.SA'},
    {'label': 'Getnet', 'value': 'GETT4.SA'},
    {'label': 'SulAmérica', 'value': 'SULA4.SA'},
    {'label': 'SulAmérica', 'value': 'SULA3.SA'},
    {'label': 'Melhoramentos', 'value': 'MSPA4.SA'},
    {'label': 'São Paulo Turismo', 'value': 'AHEB6.SA'},
    {'label': 'Karsten', 'value': 'CTKA3.SA'},
    {'label': 'MRS Logística', 'value': 'MRSA6B.SA'},
    {'label': 'Consórcio Alfa', 'value': 'BRGE5.SA'},
    {'label': 'Tronox Pigmentos', 'value': 'CRPG3.SA'},
    {'label': 'MRS Logística', 'value': 'MRSA3B.SA'},
    {'label': 'Wetzel', 'value': 'MWET3.SA'},
    {'label': 'Döhler', 'value': 'DOHL3.SA'},
    {'label': 'CELPE', 'value': 'CEPE5.SA'},
    {'label': 'Mercantil do Brasil Financeira', 'value': 'MERC3.SA'},
    {'label': 'Tecnosolo', 'value': 'TCNO4.SA'},
    {'label': 'Tecnosolo', 'value': 'TCNO3.SA'},
    {'label': 'CELPE', 'value': 'CEPE6.SA'},
    {'label': 'BKBR3', 'value': 'BKBR3.SA'},
    {'label': 'Metalgráfica Iguaçu', 'value': 'MTIG4.SA'},
    {'label': 'Blue Tech Solutions', 'value': 'BLUT4.SA'},
    {'label': 'Blue Tech Solutions', 'value': 'BLUT3.SA'},
    {'label': 'Banco Modal', 'value': 'MODL4.SA'},
    {'label': 'CARD3', 'value': 'CARD3.SA'},
    {'label': 'Investimentos Bemge', 'value': 'FIGE3.SA'},
    {'label': 'Finansinos', 'value': 'FNCN3.SA'},
    {'label': 'CASAN', 'value': 'CASN3.SA'},
    {'label': 'Teka', 'value': 'TEKA3.SA'},
    {'label': 'Hercules', 'value': 'HETA3.SA'},
    {'label': 'Locamerica', 'value': 'LCAM3.SA'},
    {'label': 'Banco Inter', 'value': 'BIDI4.SA'},
    {'label': 'Banco Inter', 'value': 'BIDI3.SA'},
    {'label': 'CEEE GT', 'value': 'EEEL4.SA'},
    {'label': 'CEEE GT', 'value': 'EEEL3.SA'},
    {'label': 'BBRK3', 'value': 'BBRK3.SA'},
    {'label': 'Sondotécnica', 'value': 'SOND3.SA'},
    {'label': 'Naturgy (CEG)', 'value': 'CEGR3.SA'},
    {'label': 'CESP', 'value': 'CESP6.SA'},
    {'label': 'CESP', 'value': 'CESP3.SA'},
    {'label': 'CESP', 'value': 'CESP5.SA'},
    {'label': 'Encorpar', 'value': 'ECPR4.SA'},
    {'label': 'Mosaico', 'value': 'MOSI3.SA'},
    {'label': 'Focus Energia', 'value': 'POWE3.SA'},
    {'label': 'Equatorial Pará', 'value': 'EQPA6.SA'},
    {'label': 'Encorpar', 'value': 'ECPR3.SA'},
    {'label': 'NotreDame Intermédica', 'value': 'GNDI3.SA'},
    {'label': 'Lojas Americanas', 'value': 'LAME4.SA'},
    {'label': 'Lojas Americanas', 'value': 'LAME3.SA'},
    {'label': 'São Paulo Turismo', 'value': 'AHEB5.SA'},
    {'label': 'Omega Geração', 'value': 'OMGE3.SA'},
    {'label': 'IGTA3', 'value': 'IGTA3.SA'},
    {'label': 'JPSA3', 'value': 'JPSA3.SA'},
    {'label': 'BRDT3', 'value': 'BRDT3.SA'},
    {'label': 'JBDU4', 'value': 'JBDU4.SA'},
    {'label': 'JBDU3', 'value': 'JBDU3.SA'},
    {'label': 'Hering', 'value': 'HGTX3.SA'},
    {'label': 'CCPR3', 'value': 'CCPR3.SA'},
    {'label': 'DTEX3', 'value': 'DTEX3.SA'},
    {'label': 'VVAR3', 'value': 'VVAR3.SA'},
    {'label': 'Dimed', 'value': 'PNVL4.SA'},
    {'label': 'Terra Santa', 'value': 'TESA3.SA'},
    {'label': 'BTOW3', 'value': 'BTOW3.SA'},
    {'label': 'Estrela', 'value': 'ESTR3.SA'},
    {'label': 'Linx', 'value': 'LINX3.SA'},
    {'label': 'Embpar', 'value': 'BTTL3.SA'},
    {'label': 'GPCP3', 'value': 'GPCP3.SA'},
    {'label': 'GPCP4', 'value': 'GPCP4.SA'},
    {'label': 'Smiles', 'value': 'SMLS3.SA'},
    {'label': 'MMX Mineração', 'value': 'MMXM3.SA'},
    {'label': 'Biosev', 'value': 'BSEV3.SA'},
    {'label': 'CNTO3', 'value': 'CNTO3.SA'},
    {'label': 'AES Tietê Energia', 'value': 'TIET4.SA'},
    {'label': 'AES Tietê Energia', 'value': 'TIET3.SA'},
    {'label': 'Corrêa Ribeiro', 'value': 'CORR4.SA'},
    {'label': 'Conservas Oderich', 'value': 'ODER4.SA'},
    {'label': 'CELPE', 'value': 'CEPE3.SA'},
    {'label': 'Adolpho Lindenberg', 'value': 'CALI4.SA'},
    {'label': 'Sansuy', 'value': 'SNSY6.SA'},
    {'label': 'CASAN', 'value': 'CASN4.SA'},
    {'label': 'EMAE', 'value': 'EMAE3.SA'},
    {'label': 'Banpará', 'value': 'BPAR3.SA'},
    {'label': 'Aliperti', 'value': 'APTI4.SA'},
    {'label': 'FCA', 'value': 'VSPT3.SA'},
    {'label': 'Metalgráfica Iguaçu', 'value': 'MTIG3.SA'},
    {'label': 'Investimentos Bemge', 'value': 'FIGE4.SA'},
    {'label': 'Trevisa', 'value': 'LUXM3.SA'},
    {'label': 'Tekno', 'value': 'TKNO3.SA'},
    {'label': 'Coelce', 'value': 'COCE6.SA'},
    {'label': 'Mangels', 'value': 'MGEL3.SA'},
    {'label': 'Santanense', 'value': 'CTSA8.SA'},
    {'label': 'Minasmáquinas', 'value': 'MMAQ4.SA'}
]